### ISSUE TITLE
option to trap/ignore broken pipe error on unexpected connection close

### ISSUE THREAD

**Issue by erjoalgo** [joaotavora/hunchensocket#19] opened 2018-05-17 03:38 UTC
If a client unexpectedly closes the connection at the wrong time, an error like the one reproduced below happens on the server. Is there an option to ignore/consume these errors without jumping to ldb? perhaps something like `hunchentoot:*catch-errors-p*`?

```
(describe 'hunchentoot:*catch-errors-p*)
HUNCHENTOOT:*CATCH-ERRORS-P*
  [symbol]

*CATCH-ERRORS-P* names a special variable:
  Value: NIL
  Documentation:
    Whether Hunchentoot should catch and log errors (or rather invoke
    the debugger).
```

```
Couldn't write to #<SB-SYS:FD-STREAM for "socket 127.0.0.1:4245, peer: 127.0.0.1:58380" {100425F663}>:
  Broken pipe
   [Condition of type SB-INT:SIMPLE-STREAM-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "hunchentoot-worker-127.0.0.1:58380" RUNNING {1004BE8A23}>)

Backtrace:
  0: (SB-IMPL::FLUSH-OUTPUT-BUFFER #<SB-SYS:FD-STREAM for "socket 127.0.0.1:4245, peer: 127.0.0.1:58380" {100425F663}>)
  1: (SB-IMPL::FINISH-FD-STREAM-OUTPUT #<SB-SYS:FD-STREAM for "socket 127.0.0.1:4245, peer: 127.0.0.1:58380" {100425F663}>)
  2: (FINISH-OUTPUT #<SB-SYS:FD-STREAM for "socket 127.0.0.1:4245, peer: 127.0.0.1:58380" {100425F663}>)
  3: ((FLET HUNCHENTOOT::CLOSE-STREAM :IN HUNCHENTOOT:PROCESS-CONNECTION) #<SB-SYS:FD-STREAM for "socket 127.0.0.1:4245, peer: 127.0.0.1:58380" {100425F663}>)
  4: ((FLET #:CLEANUP-FUN-298 :IN HUNCHENTOOT:PROCESS-CONNECTION)) [cleanup]
  5: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENSOCKET:WEBSOCKET-ACCEPTOR (host *, port 4245)> #<USOCKET:STREAM-USOCKET {100425F913}>) [fast-method]
  6: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENTOOT:ACCEPTOR T)) #<HUNCHENSOCKET:WEBSOCKET-ACCEPTOR (host *, port 4245)> #<USOCKET:STREAM-USOCKET {100425F913}>) [fast-method]
  7: ((:METHOD HUNCHENTOOT:PROCESS-CONNECTION :AROUND (HUNCHENSOCKET:WEBSOCKET-ACCEPTOR T)) #<HUNCHENSOCKET:WEBSOCKET-ACCEPTOR (host *, port 4245)> #<USOCKET:STREAM-USOCKET {100425F913}>) [fast-method]
  8: ((FLET HUNCHENTOOT::PROCESS-CONNECTION% :IN HUNCHENTOOT::HANDLE-INCOMING-CONNECTION%) #<HUNCHENSOCKET:WEBSOCKET-ACCEPTOR (host *, port 4245)> #<USOCKET:STREAM-USOCKET {100425F913}>)
  9: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
 10: ((FLET #:WITHOUT-INTERRUPTS-BODY-1139 :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 11: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE))
 12: ((FLET #:WITHOUT-INTERRUPTS-BODY-359 :IN SB-THREAD::CALL-WITH-MUTEX))
 13: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE) {7FFFBF50ED6B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THR..
 14: (SB-THREAD::INITIAL-THREAD-FUNCTION-TRAMPOLINE #<SB-THREAD:THREAD "hunchentoot-worker-127.0.0.1:58380" RUNNING {1004BE8A23}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {..
 15: ("foreign function: call_into_lisp")
 16: ("foreign function: new_thread_trampoline")
 --more--
```

**Comment by joaotavora** [comment] 2018-05-17 08:12
Posting a backtrace with no explanation of what caused it is unacceptable as an issue. I need to see the steps to reproduce the issue locally in my system, or at least an attempt to do so. The hunchensocket issue tracker is not a chat room.

This one is slightly slightly different since you did include "If a client unexpectedly closes the connection at the wrong time,". However, this is too wayyy vague. Closing until you give concrete information that can lead to reproducing the problem in my machine. Minimum is CL implementation version and steps taken starting from `sbcl --no-userinit`

**Closed by joaotavora** 2018-05-17 08:12 UTC

**Comment by erjoalgo** [comment] 2018-06-19 07:08
You closed 4 of the issues I reported stating that "the huchensocket issue tracker is not a chat room". In each of those issues, I've described the problem, when it happens, and provided a full stack trace pointing to hunchensockets internal code. I don't see where you got the sense that I am treating the issue tracker as a chat room.

I was trying to contribute to this good project, which I have used, by reporting possible issues I encountered while using it, in hopes of helping future users avoid them and improve the project. But if your attitude is that your project is already perfect and that reporting possible issues is a personal attack against you, then, definitely please ban me from the tracker, as you threatened.

----------------

If you were really interested in addressing the possible issue instead of taking it personally or assuming your project is already perfect, why not ask for further information instead of closing right away?
